object Frm_csll: TFrm_csll
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'Frm_csll'
  ClientHeight = 281
  ClientWidth = 391
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 396
    Height = 61
    TabOrder = 0
    object Cbx_venda: TCheckBox
      Left = 32
      Top = 8
      Width = 97
      Height = 17
      Caption = 'Venda'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      OnClick = Cbx_vendaClick
    end
    object Cbx_servico: TCheckBox
      Left = 32
      Top = 31
      Width = 97
      Height = 17
      Caption = 'Servi'#231'o'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = Cbx_servicoClick
    end
    object Cbx_outras: TCheckBox
      Left = 144
      Top = 8
      Width = 145
      Height = 17
      Caption = 'Outras Al'#237'quotas'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      OnClick = Cbx_outrasClick
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 54
    Width = 396
    Height = 127
    TabOrder = 1
    object Label1: TLabel
      Left = 20
      Top = 66
      Width = 83
      Height = 19
      Caption = 'Base CSLL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label2: TLabel
      Left = 20
      Top = 13
      Width = 133
      Height = 19
      Caption = 'Base Bruta CSLL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label3: TLabel
      Left = 243
      Top = 13
      Width = 113
      Height = 19
      Caption = 'Al'#237'quota Base'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label4: TLabel
      Left = 243
      Top = 66
      Width = 69
      Height = 19
      Caption = 'Al'#237'quota'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object edt_base_bruta: TEdit
      Left = 24
      Top = 38
      Width = 121
      Height = 22
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      Text = '0'
      OnExit = edt_base_brutaExit
      OnKeyPress = edt_base_brutaKeyPress
    end
    object Edt_aliq: TEdit
      Left = 244
      Top = 38
      Width = 89
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      Text = '0'
      OnExit = Edt_aliqExit
      OnKeyPress = Edt_aliqKeyPress
    end
    object Edt_base: TEdit
      Left = 24
      Top = 91
      Width = 121
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      Text = '0'
      OnKeyPress = Edt_baseKeyPress
    end
    object Edt_aliq_final: TEdit
      Left = 243
      Top = 91
      Width = 89
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 3
      Text = '0'
      OnExit = Edt_aliq_finalExit
      OnKeyPress = Edt_aliq_finalKeyPress
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 173
    Width = 396
    Height = 151
    TabOrder = 2
    object Label8: TLabel
      Left = 23
      Top = 70
      Width = 112
      Height = 19
      Caption = 'Total da CSLL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label9: TLabel
      Left = 141
      Top = 71
      Width = 26
      Height = 18
      Caption = 'R$:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Btn_calcu: TButton
      Left = 104
      Top = 22
      Width = 73
      Height = 25
      Caption = 'Calcular'
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      OnClick = Btn_calcuClick
    end
    object Button3: TButton
      Left = 183
      Top = 22
      Width = 73
      Height = 25
      Caption = 'Limpar'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = Button3Click
    end
    object Edt_resultado: TEdit
      Left = 173
      Top = 64
      Width = 129
      Height = 33
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      Text = '0'
    end
  end
end
